### ISSUE TITLE
Add Nanasi-CSS to NPM

### ISSUE THREAD

**Issue by alphaolomi** [gxvr/Nanasi-CSS#8]
First check out this tutorial:https://zellwk.com/blog/publish-to-npm/ 

Steps
1. Make an account in [npm](https://www.npmjs.com/) Choose username carefully u cant change it
2. `npm login`
3. `npm publish`
4.  Kindly add as maintainer

**Comment by gxvr** [comment]
Sure thing! will do so starting on version 1.1. Planning to rewrite some rules especially for mobile responsiveness
